FROM python:3.11

RUN apt-get update && apt-get install -y libhdf5-dev

WORKDIR /

EXPOSE 3000

COPY ./requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt

COPY ./backend /backend

CMD ["uvicorn", "backend.main:app", "--host=0.0.0.0", "--port=3000", "--workers=2"]
